version: 2.1

jobs:
  build:
    docker:
      - image: dart:latest

    steps:
      - checkout

      # Set up Dart environment
      - run: dart pub get

      # Run tests
      - run: RiceCookerTest.dart

workflows:
  version: 2
  build:
    jobs:
      - build
