version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.0

    steps:
      - checkout

      # Ensure the gradlew script has execute permissions
      - run:
          name: Grant Execute Permissions
          command: chmod +x ./gradlew

      # Install dependencies and set up the Kotlin environment
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y \
              unzip \
              && curl -sSL https://get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install kotlin

      # Run linting
      - run:
          name: Run KtLint
          command: ./gradlew ktlintCheck

      # Run tests
      - run:
          name: Run Tests
          command: ./gradlew test
