version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.21.5 

    working_directory: /go/src/github.com/miharyjoe/cc-d4-rice-cooker-ci-miharyjoe.git

    steps:
      - checkout

      # Download and install dependencies
      - run: go mod download

      # Run tests
      - run: go test -v ./...

workflows:
  version: 2
  build:
    jobs:
      - build
