version: 2.1

jobs:
  build:
    docker:
      - image: google/dart

    steps:
      - checkout

      # Set up Dart environment
      - run: dart pub add test/test.dart

      # Run tests
      - run: RiceCookerTest.dart

workflows:
  version: 2
  build:
    jobs:
      - build
